services:
  - type: web
    name: mood-music-backend
    env: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true

  - type: static
    name: mood-music-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
